apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yml
- statefulset.yml
configMapGenerator:
- name: my-db-env # {"$kpt-set":"db-env"}
  behavior: create
  literals:
  - "BITNAMI_DEBUG=false"
  - "POSTGRESQL_PORT_NUMBER=5432"
  - "POSTGRESQL_VOLUME_DIR=/bitnami/postgresql"
  - "PGDATA=/bitnami/postgresql/data"
  - "POSTGRESQL_ENABLE_LDAP=no"
  - "POSTGRESQL_ENABLE_TLS=no"
- name: my-db-init # {"$kpt-set":"db-init"}
  behavior: create
  files: []
