apiVersion: v1
kind: Service
metadata:
  name: my-db-headless # {"$kpt-set":"headless_service"}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: tcp-postgresql
    port: 5432
    targetPort: tcp-postgresql
  selector:
    app: postgresql
