apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-db # {"$kpt-set":"name"}
spec:
  serviceName: my-db-headless # {"$kpt-set":"headless_service"}
  replicas: 1
  selector:
    matchLabels:
      app: my-db # {"$kpt-set":"name"}
  template:
    metadata:
      name: my-db # {"$kpt-set":"name"}
      labels:
        app: my-db # {"$kpt-set":"name"}
    spec:
      securityContext:
        fsGroup: 1001
      containers:
        - name: postgresql
          image: docker.io/bitnami/postgresql:11.9.0-debian-10-r1
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsUser: 1001
          envFrom:
            - configMapRef:
                name: my-db-env # {"$kpt-set":"db-env"}
          ports:
            - name: tcp-postgresql
              containerPort: 5432
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U postgres
            initialDelaySeconds: 30
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U postgres
            initialDelaySeconds: 15
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: my-db-data # {"$kpt-set":"db-data"}
              mountPath: /bitnami/postgresql
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
  volumeClaimTemplates:
    - metadata:
        name: my-db-data # {"$kpt-set":"db-data"}
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "5Gi"
