apiVersion: v1
kind: Service
metadata:
  name: postgres-postgresql
spec:
  type: ClusterIP
  ports:
  - name: tcp-postgresql
    port: 5432
    targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/name: postgresql
    role: master
