apiVersion: apps/v1
kind: Deployment
metadata:
  name: app # {"$kpt-set":"name"}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: app # {"$kpt-set":"name"}
  template:
    metadata:
      labels:
        app: app # {"$kpt-set":"name"}
    spec:
      serviceAccountName: default
      # FIXME: update wito3030/nano to be non-root
      # securityContext:
      #   runAsNonRoot: true
      containers:
        - name: app # {"$kpt-set":"name"}
          image: wito3030/nano:latest # {"$kpt-set":"image-with-tag"}
          ports:
            - name: http
              containerPort: 8080
          # FIXME: update wito3030/nano to use /health
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 15
          envFrom:
            - configMapRef:
                name: app-env # {"$kpt-set":"env"}
          resources:
            requests:
              cpu: 40m # {"$kpt-set":"cpu"}
              memory: 100Mi # {"$kpt-set":"mem"}
