apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomerium
spec:
  template:
    spec:
      containers:
      - name: pomerium
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
