apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-db # {"$kpt-set":"name"}
spec:
  template:
    metadata:
      name: my-db # {"$kpt-set":"name"}
    spec:
      containers:
      - name: postgresql
        resources:
          requests:
            cpu: 250m # {"$kpt-set":"cpu"}
            memory: 256Mi # {"$kpt-set":"mem"}
          limits:
            cpu: 250m # {"$kpt-set":"cpu"}
            memory: 256Mi # {"$kpt-set":"mem"}
