apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
patchesStrategicMerge:
- patches/add-init.yml
- patches/add-resources.yml
resources:
- ../upstream
configMapGenerator:
- name: my-db-env # {"$kpt-set":"db-env"}
  behavior: merge
  literals:
  - "POSTGRES_PASSWORD=postgres" # {"$kpt-set":"password_env"}
- name: my-db-init # {"$kpt-set":"db-init"}
  behavior: merge
  files:
  - init.sql=config/init.sql
