apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../upstream
configMapGenerator:
  - name: postgresql-env
    behavior: merge
    literals:
      - "POSTGRES_USER=user" # {"$kpt-set":"user-env"}
      - "POSTGRES_PASSWORD=didid" # {"$kpt-set":"password-env"}
      - "POSTGRES_DB=didid" # {"$kpt-set":"database-env"}
      - "POSTGRES_POSTGRES_PASSWORD=didid" # {"$kpt-set":"admin-password-env"}
