apiVersion: v1
kind: Service
metadata:
  name: app # {"$kpt-set":"name"}
spec:
  selector:
    app: app # {"$kpt-set":"name"}
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
