apiVersion: v1
kind: Service
metadata:
  name: minio # {"$kpt-set":"name"}
spec:
  ports:
  - name: http-web
    port: 80
    targetPort: 9000
    protocol: TCP
  selector:
    app: minio # {"$kpt-set":"name"}
